
version = 1

[[annotations]]
path = "REUSE.toml"
SPDX-FileCopyrightText = "2024 DS"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "textures/bed_rock_pillowmask_*.png"
SPDX-FileCopyrightText = "2024 DS"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "textures/bed_rock_invimg.png"
SPDX-FileCopyrightText = "2024 DS"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "screenshot.png"
SPDX-FileCopyrightText = "2024 Minetest Game contributors"
SPDX-License-Identifier = "CC-BY-SA-3.0 AND CC-BY-SA-4.0"
